listener 1883
allow_anonymous true

persistence true
persistence_location /mosquitto/data/

log_dest stdout
log_dest file /mosquitto/log/mosquitto.log

# Maximum complete MQTT packet: 16 MB
max_packet_size 16000000

# Maximum message payload: 12 MB
message_size_limit 12000000